### ISSUE TITLE
Error 404 when starting homebridge

### ISSUE THREAD

**Issue by a728432** [NorthernMan54/homebridge-connex#3]
When I start the plugin, I am receiving a 404 error when polling devices (although it looks like it is successfully retrieving some of my info).  

Output is below - any suggestions?

_getZone Error  404
pollDevices Error: Error: HTTP Error:
    at /homebridge/node_modules/homebridge-connex/lib/connex.js:143:18
    at Ticket.<anonymous> (/homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/queue.js:234:41)
    at Ticket.emit (events.js:223:5)
    at Ticket.finish (/homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/ticket.js:57:8)
    at /homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/tickets.js:10:16
    at Array.forEach (<anonymous>)
    at Tickets._apply (/homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/tickets.js:9:16)
    at Tickets.<computed> [as finish] (/homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/tickets.js:30:10)
    at Worker.<anonymous> (/homebridge/node_modules/homebridge-connex/node_modules/better-queue/lib/queue.js:640:23)
    at Worker.emit (events.js:223:5) {
  product_name: 'Dimplex CONNEX®',
  model: 'AY001MUS1',
  dsn: 'AC000W001462284',
  oem_model: 'H1417US',
  sw_version: 'bc 1.15 09/17/15 15:32:37 ID a11190c',
  template_id: 130,
  mac: 'e04f4305c8aa',
  unique_hardware_id: null,
  hwsig: '001c002e-35355109-35373832',
  lan_ip: '***',
  connected_at: '2020-01-09T21:40:30Z',
  key: 24314327,
  lan_enabled: false,
  has_properties: true,
  product_class: null,
  connection_status: 'Online',
  lat: '***',
  lng: '***',
  locality: 'L******',
  device_type: 'Wifi',
  zones: { Z1: { name: 'Theatre' }, Z2: { name: 'Fitness Room' } }
}

**Comment by NorthernMan54** [comment]
How many zones do you have configured?  Just 2?

**Comment by a728432** [comment]
Thats correct - only 2

**Comment by NorthernMan54** [comment]
I think the 404 is from zone 3 and 4.

Does it work otherwise?

**Comment by a728432** [comment]
No - I don't see the thermostat get created in HomeKit (but can other platforms/accessories)

Should I create 2 dummy zones for 3 and 4?

**Comment by a728432** [comment]
FYI - I created names for zones 3 and 4 in the iOS app and it was able to load

**Comment by NorthernMan54** [comment]
Awesome

I made a change to no longer error out for missing names, so no one else should have the same issue
