### ISSUE TITLE
Cloud offline error

### ISSUE THREAD

**Issue by steveintro** [NorthernMan54/homebridge-connex#6]
Hi there-

Getting a "Cloud Offline" error- can't figure out why this is but it's crashing my entire homebridge. This is from the log (deleted some sensitive data):

5/31/2020, 9:48:09 PM Error: _getZones Error: ETIMEDOUT
5/31/2020, 9:48:09 PM at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-connex/node_modules/request/request.js:848:19)
5/31/2020, 9:48:09 PM at listOnTimeout (internal/timers.js:531:17)
5/31/2020, 9:48:09 PM at processTimers (internal/timers.js:475:7) {
5/31/2020, 9:48:09 PM code: 'ETIMEDOUT',
5/31/2020, 9:48:09 PM connect: true
5/31/2020, 9:48:09 PM }
5/31/2020, 9:48:09 PM pollDevices Error: Error: ETIMEDOUT
5/31/2020, 9:48:09 PM at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-connex/node_modules/request/request.js:848:19)
5/31/2020, 9:48:09 PM at listOnTimeout (internal/timers.js:531:17)
5/31/2020, 9:48:09 PM at processTimers (internal/timers.js:475:7) {
5/31/2020, 9:48:09 PM code: 'ETIMEDOUT',
5/31/2020, 9:48:09 PM connect: true
5/31/2020, 9:48:09 PM } {
5/31/2020, 9:48:09 PM product_name: 'Dimplex CONNEX®',
5/31/2020, 9:48:09 PM model: 'AY001MUS1',
5/31/2020, 9:48:09 PM dsn: 'AC000W001463021',
5/31/2020, 9:48:09 PM oem_model: 'H1417US',
5/31/2020, 9:48:09 PM sw_version: 'bc 1.15 09/17/15 15:32:37 ID a11190c',
5/31/2020, 9:48:09 PM template_id: 130,
5/31/2020, 9:48:09 PM mac: '',
5/31/2020, 9:48:09 PM unique_hardware_id: null,
5/31/2020, 9:48:09 PM hwsig: '',
5/31/2020, 9:48:09 PM lan_ip: '',
5/31/2020, 9:48:09 PM connected_at: '2020-05-31T12:14:36Z',
5/31/2020, 9:48:09 PM key:,
5/31/2020, 9:48:09 PM lan_enabled: false,
5/31/2020, 9:48:09 PM has_properties: true,
5/31/2020, 9:48:09 PM product_class: null,
5/31/2020, 9:48:09 PM connection_status: 'Online',
5/31/2020, 9:48:09 PM lat: '',
5/31/2020, 9:48:09 PM lng: '-',
5/31/2020, 9:48:09 PM locality: '',
5/31/2020, 9:48:09 PM device_type: 'Wifi',
5/31/2020, 9:48:09 PM zones: { Z1: { name: 'Bedroom' }, Z2: { name: 'Upstairs Hallway' } }
5/31/2020, 9:48:09 PM }
5/31/2020, 9:48:09 PM [connex2] ERROR: pollDevices Error: ETIMEDOUT
    at Timeout.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-connex/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT',
  connect: true
} {
  product_name: 'Dimplex CONNEX®',
  model: 'AY001MUS1',
  dsn: 'AC000W001463021',
  oem_model: 'H1417US',
  sw_version: 'bc 1.15 09/17/15 15:32:37 ID a11190c',
  template_id: 130,
  mac: '',
  unique_hardware_id: null,
  hwsig: '',
  lan_ip: '192.168.1.25',
  connected_at: '2020-05-31T12:14:36Z',
  key:,
  lan_enabled: false,
  has_properties: true,
  product_class: null,
  connection_status: 'Online',
  lat: '',
  lng: '',
  locality: '',
  device_type: 'Wifi',
  zones: { Z1: { name: 'Bedroom' }, Z2: { name: 'Upstairs Hallway' } }
}
5/31/2020, 9:48:09 PM (node:16028) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Setpoint' of undefined
5/31/2020, 9:48:09 PM at connexPlatform.updateStatus (/home/hoobs/.hoobs/node_modules/homebridge-connex/index.js:104:34)
5/31/2020, 9:48:09 PM at connexPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-connex/index.js:63:20)
5/31/2020, 9:48:09 PM at Array.forEach (<anonymous>)
5/31/2020, 9:48:09 PM at connexPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-connex/index.js:60:19)
5/31/2020, 9:48:09 PM at /home/hoobs/.hoobs/node_modules/homebridge-connex/lib/connex.js:91:5
5/31/2020, 9:48:09 PM at connex.pollDevices (/home/hoobs/.hoobs/node_modules/homebridge-connex/lib/connex.js:111:5)
5/31/2020, 9:48:09 PM at runMicrotasks (<anonymous>)
5/31/2020, 9:48:09 PM at processTicksAndRejections (internal/process/task_queues.js:93:5)
5/31/2020, 9:48:09 PM (node:16028) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)

thank you!

-Steve

**Comment by NorthernMan54** [comment]
Was it working and suddenly stopped or is this first time setup?

Is your internet connection solid?  Error is a timeout connecting to CONNEX cloud

**Comment by steveintro** [comment]
Working and suddenly stopped... internet connection still up. Tried restarting everything.

CONNEX app works as well. 

Steve Intrabartola
516.807.3403
steveintro@gmail.com
http://steveintro.com

**Comment by NorthernMan54** [comment]
How many zones do you have configured?
